apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-github
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  target:
    name: argocd-repo-creds-github
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: "https://github.com/TourinhoM"
        githubAppID: "{{ .appId }}"
        githubAppInstallationID: "{{ .installationId }}"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: appId
      remoteRef:
        key: e9ec0e18-628a-4230-8467-b44a01134382
    - secretKey: installationId
      remoteRef:
        key: a342d06f-78e0-4e82-80e9-b44a01153f72
    - secretKey: privateKey
      remoteRef:
        key: 14ef6cac-4887-460c-9a78-b44a0115627c
