apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Plano:
# - Manter apenas CRDs do Argo CD aqui (AppProject/Application/ApplicationSet)
# - Cada Application deve apontar para um path em `envs/<ambiente>/...`

resources:
  - projects/platform.yaml
  - applications/argocd-self.yaml
  - applications/external-secrets.yaml
  - applications/external-secrets-config.yaml
  - applications/infra-postgresql.yaml
  - applications/infra-keycloak.yaml
  - applications/infra-ollama.yaml
  - applications/monitoring.yaml
  - applications/monitoring-dashboards.yaml

